### ISSUE TITLE
helper input_number not writeable

### ISSUE THREAD

**Issue by Continueless** [ioBroker/ioBroker.hass#106]
Hello !!

the helpers of type input_text are writeable, but the helpers of type input_number not. why ?

greetz :)

**Comment by Apollon77** [comment]
The generic answer without more logs: because it is reported by Hass to be that way (befause we just realize what is sent by the definitions the hass api reports).

If you want to know it more detailed please provide debug logs from an adaopter startand ideally try to write such a value or tell the exact name and such.

**Comment by Continueless** [comment]
okay, dann frage ich das mal anders: Wenn Homeassistant das so ausgibt als nicht beschreibbar, warum kann man es denn über jedes node-red beschreiben, auch vom node red adapter von iobroker, aber mit dem homeassistant adapter nicht ?

**Comment by Apollon77** [comment]
Dann antworte ich mal so ... Ich habe das mnode-red nicht geschrieben also weiss ich das nicht.

Ich wiederhole damit:
> If you want to know it more detailed please provide debug logs from an adaopter startand ideally try to write such a value or tell the exact name and such.
